### ISSUE TITLE
Rename "CipI/R" to "CipNS"

### ISSUE THREAD

**Issue by vLSHTM** [zadyson/TyphiNET#30]
In the consortium paper we used the term ‘ciprofloxacin non-susceptible (cipNS)’ rather than cipI/R.
I think we should update the dashboard accordingly, so that wherever it currently says ‘CipI/R’ it should instead be ‘CipNS’ - Kat Holt

**Comment by lcerdeira** [comment]
Hi @zadyson many thanks, now I managed to add @vLSHTM

**Comment by lcerdeira** [comment]
Renamed
